### ISSUE TITLE
addIndex run time too long

### ISSUE THREAD

**Issue by xqx1568** [AhmadSakor/falcon#10]
When I use entitiesIndexAdd() to build elasticsearch, it runs 18 hours but it's only done 2/3.
Could you give me some help?

**Comment by xqx1568** [comment]
I delete the **print** command, and add threads. It has finished now.

**Comment by AhmadSakor** [comment]
Hello
thanks for your interest in our work.
actually we are using now ElasticDump for this task. It can import and export the index very fast.
https://github.com/elasticsearch-dump/elasticsearch-dump

Also you can check  Falcon 2.0 that can link to Wikidata as well
