### ISSUE TITLE
How to configure endpoint for DBpedia and elasticsearch

### ISSUE THREAD

**Issue by Denescor** [AhmadSakor/falcon#4]
Hello

I try to install falcon in order to test it but, even when I put elasticsearch dump into a localhost directory (and change the http address in the elasticsearch initialization), the system is unable to find the index. If I try to create a new index, I have a HTTP request error of type "_PUT request is not authorized_".
I didn't succeed resolving the problem, I cannot perform the model.

So, I think my endpoint configuration is bad but I don't know how to do it.

What is the process to configure endpoint for elasticsearch and DBpedia ?

Thanks for your responses.

**Comment by AhmadSakor** [comment]
Hello,
 the best practice is to use docker images for DBpedia and elasticsearch.
once you have the endpoints running you can create the indices and push the dump using elasticdump.

This is the body of the PUT request to create the index
```
{
"settings" : {
        "number_of_shards" : 3,
        "number_of_replicas" : 1
    },
    "mappings": {
    "doc": {
      "properties": {
        "uri": {
          "type": "keyword"
        },
        "label": {
          "type": "text"
        }
      }
    }
  }
}

```
