### ISSUE TITLE
Missing csv and json files in the data folder for evaluation 

### ISSUE THREAD

**Issue by rrichajalota** [AhmadSakor/falcon#6]
Hello @AhmadSakor, could you please provide the LcQuAD and QALD datasets that were used for evaluation?   
There are two versions for LcQuAD and I am not sure which one was used.

**Comment by AhmadSakor** [comment]
Hello @rrichajalota 
The datasets and the evaluation results are uploaded now
thanks for your interest

**Comment by rrichajalota** [comment]
Thanks, @AhmadSakor. Could you please share the link here? Unfortunately, I am not able to see the uploaded files in the data folder even now. :/

**Comment by rrichajalota** [comment]
Oh nevermind, I see it now: https://github.com/AhmadSakor/falcon/tree/master/datasets

**Comment by AhmadSakor** [comment]
Hey
They are in datasets and evaluation_results folders
